services:
  portfolio:
    build: .
    container_name: portfolio
    ports:
      - "9989:9989"
    environment:
      - PORT=9989
      - DATA_DIR=/data/portfolio.db
      - ADMIN_USER=admin
      - ADMIN_PASS=asd2335979545
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/nvme0n1-4/portfolio/data:/data
    restart: unless-stopped
